# Create a CSV

- using pandas we can create a CSV file from a DataFrame

In [6]:
# for creating a CSV file
import pandas as pd
# create a DataFrame
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "City": ["New York", "Los Angeles", "Chicago"]
} 
df = pd.DataFrame(data)
# save the DataFrame to a CSV file
df.to_csv("people.csv", index=False)

In [7]:
# use header Function to change the header of a CSV file
df.to_csv("people_with_header.csv", header=["Full Name", "Years", "Location"], index=False)
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [8]:
# use the `columns` parameter to select specific columns
df.to_csv("people_selected_columns.csv", columns=["Name", "City"], index=False)
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [ ]:
# use the `mode` parameter to append to an existing file
df.to_csv("people_append.csv", mode='a', header=False, index=False)
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [ ]:

# use the `encoding` parameter to specify the encoding
df.to_csv("people_utf8.csv", encoding='utf-8', index=False)
# use the `compression` parameter to compress the file
df.to_csv("people_compressed.csv.gz", compression='gzip', index=False)
# use the `quotechar` parameter to specify the character used for quoting
df.to_csv("people_quoted.csv", quotechar='"', index=False)
# use the `line_terminator` parameter to specify the line terminator
df.to_csv("people_custom_line_terminator.csv", line_terminator='\n', index=False)
# use the `date_format` parameter to specify the date format
df['Date'] = pd.to_datetime(['2023-01-01', '2023-02-01', '2023-03-01'])
df.to_csv("people_with_date.csv", date_format='%Y-%m-%d', index=False)
# use the `float_format` parameter to specify the format for floating point numbers
df['Salary'] = [50000.5, 60000.75, 70000.25]
df.to_csv("people_with_salary.csv", float_format='%.2f', index=False)