# Data Frame

In [4]:
import pandas as pd

In [5]:
l=[1,2,3,4,5]
var=pd.DataFrame(l)
print(var)

   0
0  1
1  2
2  3
3  4
4  5

`We can also use Dictionary for Data_Frame`

In [7]:
d={"Name":['Atif','Ahmad','Umer','Aslam'],
   "age":[20,21,19,22]
}
var2=pd.DataFrame(d)
var2

    Name  age
0   Atif   20
1  Ahmad   21
2   Umer   19
3  Aslam   22

# Call a specific Column

In [9]:
var2=pd.DataFrame(d,columns=["Name"])
print(var2)

    Name
0   Atif
1  Ahmad
2   Umer
3  Aslam

In [10]:
var2=pd.DataFrame(d,columns=["age"])
var2

   age
0   20
1   21
2   19
3   22

`Call multiple columns`

In [13]:
var2=pd.DataFrame(d,columns=['age','Name'])
print(var2)

   age   Name
0   20   Atif
1   21  Ahmad
2   19   Umer
3   22  Aslam

In [15]:
print(var2["Name"][0])

Atif

In [17]:
import pandas as pd
l=[[1,2,3,4,5,6],[5,6,7,8,9,10]]
a=pd.DataFrame(l)
print(a)

   0  1  2  3  4   5
0  1  2  3  4  5   6
1  5  6  7  8  9  10

# Indexing

In [18]:
print(a[5][0])
print(a[5][1])

6
10