# Delete and Insert Function

# `Insert`

- we can insert dictionary items using the `insert` method

In [10]:
dict = {}
# Example of inserting items into a dictionary
def insert(key, value):
    dict[key] = value
insert(1, "List")
insert(2, "Tuple")
insert(3, "Set")
insert(4, "Dictionary")
insert(5, "String")

dict

{1: 'List', 2: 'Tuple', 3: 'Set', 4: 'Dictionary', 5: 'String'}

In [11]:
import pandas as pd
dict=pd.DataFrame({"A":[1,2,3,4,5],"B":[6,7,8,9,10]})
dict

   A   B
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10

In [12]:
dict.insert(1,"List",[1,3,5,7,9])
print(dict)

   A  List   B
0  1     1   6
1  2     3   7
2  3     5   8
3  4     7   9
4  5     9  10

In [13]:
dict.insert(3,"Copy_A",dict["A"])
print(dict)

   A  List   B  Copy_A
0  1     1   6       1
1  2     3   7       2
2  3     5   8       3
3  4     7   9       4
4  5     9  10       5

In [14]:
dict["Slice_A"]=dict["A"][:3]
print(dict)

   A  List   B  Copy_A  Slice_A
0  1     1   6       1      1.0
1  2     3   7       2      2.0
2  3     5   8       3      3.0
3  4     7   9       4      NaN
4  5     9  10       5      NaN

# `Delete`

- we can delete items from a dictionary using the `pop` method

In [16]:
dict = {"A":1, "B":2, "C":3, "D":4, "E":5}
dict.pop("A")
print(dict)

{'B': 2, 'C': 3, 'D': 4, 'E': 5}

In [17]:
import pandas as pd
list=pd.DataFrame({"A":[1,2,3,4],"B":[5,6,7,8],"C":[10,11,12,13]})
print(list)

   A  B   C
0  1  5  10
1  2  6  11
2  3  7  12
3  4  8  13

In [18]:
list.pop("A")
print(list)

   B   C
0  5  10
1  6  11
2  7  12
3  8  13

In [19]:
del list["C"]
list

   B
0  5
1  6
2  7
3  8